apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api-assignment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-api-assi
  template:
    metadata:
      labels:
        app: cloud-api-assi
    spec:
      containers:
      - name: cloud-api-container
        image: 905418098244.dkr.ecr.us-east-1.amazonaws.com/cloud-api-assignment:latest
        ports:
        - containerPort: 5000